### ISSUE TITLE
Socket closed

### ISSUE THREAD

**Issue by fibin** [iakashpaul/peerjsipx#1]
After `Socket open` event, a can do a connection between two users. But about 1 min after this event I get `Socket closed. Lost connection to server.` How to fix that?

**Comment by iakashpaul** [comment]
I think that issue would be related to the Heroku free-tier plan, where they don't keep the connection alive. Are you using Heroku as well? Try switching to another vendor or a paid plan to avoid that & also use the latest PeerJS update in npm, new maintainer has posted fixes to other issues too.

**Comment by fibin** [comment]
Yes, I'm using host server from the example. That is the problem, I guess
